### ISSUE TITLE
Adding workspaces automatically when we do bolt init

### ISSUE THREAD

**Issue by sendilkumarn** [boltpkg/bolt#119]
| Title               | Description
| --------------------|------------
| Version             | any
| Type                | feature request
| node                | any
| Operating System    | any
| Short Description   | Add workspaces automatically if there are any folders available (with package.json or child directory)
| Detailed description| It would be super awesome if we can add the workspaces automatically when we run `bolt init` for now. Later we can also fetch the child directories package.json and take the common dependencies and add them in here.

**Comment by lukebatchelor** [comment]
I like this idea.

Maybe instead of doing it silently/automatically it would output something like

```
$ bolt init
Bolt repository intitialized, you now need to add a "bolt" config to your project "package.json"
{
  /* ... */
  "bolt": {
     "workspaces": [
        "packages/*",
      ]
   }
}
```

and we could prefill the config depending on where it looks like workspaces might be?

Alternatively, Since I think there is some inquirer stuff coming in already, we could just ask the user
```
$ bolt init
Workspaces pattern: (packages/*): <input>
```
Give it a default but ask them for it when they run init.

The second would definitely be nicer, maybe can wait till `yarn version` is in?

**Comment by sendilkumarn** [comment]
My vote is also for the second option. It gives a clearer picture and higher control to the users.

**Comment by thejameskyle** [comment]
I think we should ask:

> "Do you want to use workspaces? (Y/n)"

If they say yes just fill in:

```json
{
  "bolt": {
     "workspaces": [
        "packages/*",
      ]
   }
}
```

Otherwise do nothing.

I don't think we should try to make an entire CLI to configure workspaces because I don't see a very elegant way of doing everything you'd want to do.

Also if they already have `package.json#bolt#workspaces` configured don't bother asking the question.

**Comment by sendilkumarn** [comment]
> Also if they already have package.json#bolt#workspaces configured don't bother asking the question.

of course yes, the pain point is now when the project is initiated, I have to manually add bolt#workspaces in the project. 

Else we can add this behind a flag, so users can use it when they need it
