### ISSUE TITLE
Bolt does not wire up workspace packages' clis

### ISSUE THREAD

**Issue by padmaia** [boltpkg/bolt#187]
| Title               | Bolt does not wire up workspace packages' clis
| --------------------|------------
| Version             | 0.20.7
| Type                | Issue
| node                | 8.11.3
| Operating System    | macOS 10.13.6
| Short Description   | Bolt does not seem to wire up clis exposed by workspace packages. See https://github.com/padmaia/bolt-package-with-cli-broken for a minimal reproducible example.

**Comment by lukebatchelor** [comment]
Ha. Damn. We literally ran into this just now...
I might try to take a look on the weekend or next week if you don't get to it first.

We'll work around it for now

**Comment by lukebatchelor** [comment]
Oh, I misunderstood this issue again, this *was* fixed in #191 .

The issue that's not fixed is adding workspace binaries to the Projects binary too.
Actually, I need to double check whether it should. Either way, workspaces that have dependencies on each other will have binaries symlinked now (bolt 0.21.1).

https://github.com/boltpkg/bolt/blob/593937a6055f89d707e2321accb438e2adbf3b33/src/commands/__tests__/install.test.js#L143

**Comment by lukebatchelor** [comment]
So I completely misunderstood this a few times. It was *definitely* fixed in #194 and released in bolt 0.22.2 for anyone looking
