### ISSUE TITLE
Supported yarn version?

### ISSUE THREAD

**Issue by lukebatchelor** [boltpkg/bolt#53]
I just tried running bolt on a different machine with yarn 0.22.x installed and it fails to run any lifecycle events.

Looks like

```
yarn run -s script
```

Doesnt work properly in older yarns. Do we want to support that?

We can make it

```
yarn run script -s -- other args
```

And that should be compatible with both.

**Comment by treshugart** [comment]
It would be great to do one of the following:

1. Add `yarn` as a `peerDependency` so consumers at least know they need it and which version they need. I and others have had version mismatch issues but didn't know it at first until digging really deep or hail-mary-updating `yarn`.
2. Install yarn as a `dependency` and whenever we call out to it, use the local version instead of a globally installed version.

I've talked to @thejameskyle about option 2 in the past, and I think that'd be the preferred option if nothing is blocking it.

**Comment by jameslnewell** [comment]
Was also on `0.22.x` and putting up with a heap of weirdness

**Comment by thejameskyle** [comment]
> Install yarn as a dependency and whenever we call out to it, use the local version instead of a globally installed version.

We should do this sooner rather than later
